<?php

declare(strict_types=1);

namespace App\Infrastructure\Exports;

use App\Application\DTOs\ReportResult;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithCustomValueBinder;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use PhpOffice\PhpSpreadsheet\Cell\Cell;
use PhpOffice\PhpSpreadsheet\Cell\DataType;
use PhpOffice\PhpSpreadsheet\Cell\DefaultValueBinder;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

/**
 * XLSX export of a ReportResult — REPORTS.md section 5.
 *
 * FORMULA INJECTION. PhpSpreadsheet's default binder turns any string starting
 * with "=" into a live formula. Guest names and feedback comments are free text,
 * so a comment such as =HYPERLINK("http://evil","click") would execute when the
 * administrator opens the file. This binder writes every string as literal text;
 * only genuine numbers are stored as numbers.
 */
class ReportExport extends DefaultValueBinder implements FromArray, ShouldAutoSize, WithCustomValueBinder, WithStyles, WithTitle
{
    /** Row index (1-based) of the column headings, after the metadata block. */
    private int $headingRow = 1;

    public function __construct(
        private readonly ReportResult $report,
        private readonly string $generatedBy,
        private readonly string $generatedAt,
    ) {}

    public function array(): array
    {
        $r = $this->report;

        // Header block required on every export: report, range, who, when, institution.
        $out = [
            [$r->title],
            [config('gh.institution').', '.config('gh.city')],
            ['Period', $this->date($r->from).' to '.$this->date($r->to)],
            ['Generated by', $this->generatedBy],
            ['Generated at', $this->generatedAt],
        ];

        if ($r->scopeLabel !== null) {
            $out[] = ['Scope', $r->scopeLabel];
        }

        foreach ($r->summary as $label => $value) {
            $out[] = [$label, $value];
        }

        $out[] = [];
        $out[] = array_values($r->columns);
        $this->headingRow = count($out);

        foreach ($r->rows as $row) {
            $line = [];
            foreach (array_keys($r->columns) as $key) {
                $v = $row[$key] ?? null;
                // Numeric columns go out as numbers so the file can be summed.
                $line[] = in_array($key, $r->numeric, true) && is_numeric($v) ? $v + 0 : $v;
            }
            $out[] = $line;
        }

        foreach ($r->notes as $note) {
            $out[] = [];
            $out[] = [$note];
        }

        return $out;
    }

    public function bindValue(Cell $cell, mixed $value): bool
    {
        if (is_string($value)) {
            $cell->setValueExplicit($value, DataType::TYPE_STRING);

            return true;
        }

        return parent::bindValue($cell, $value);
    }

    public function styles(Worksheet $sheet): array
    {
        return [
            1 => ['font' => ['bold' => true, 'size' => 14]],
            $this->headingRow => ['font' => ['bold' => true]],
        ];
    }

    public function title(): string
    {
        return mb_substr($this->report->title, 0, 31);   // Excel's sheet-name limit
    }

    private function date(string $ymd): string
    {
        return \Illuminate\Support\Carbon::parse($ymd)->format('d/m/Y');
    }
}
