<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $report->title }}</title>
    <style>
        /* DomPDF: DejaVu Sans carries the rupee sign; core PDF fonts do not. */
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 9px; color: #14181f; }
        h1 { font-size: 15px; margin: 0 0 2px; color: #16283e; }
        .meta { color: #4b5563; margin-bottom: 10px; }
        .meta td { padding: 1px 12px 1px 0; }
        .summary { margin: 6px 0 10px; }
        .summary td { border: 1px solid #e7e5e0; padding: 4px 8px; }
        table.data { width: 100%; border-collapse: collapse; }
        table.data th { background: #1d3452; color: #fff; text-align: left; padding: 4px; font-weight: bold; }
        table.data td { border-bottom: 1px solid #e7e5e0; padding: 3px 4px; vertical-align: top; }
        .num { text-align: right; }
        .notes { margin-top: 10px; color: #6b7484; }
        .footer { position: fixed; bottom: -10px; left: 0; right: 0; font-size: 8px; color: #9aa1ad; }
    </style>
</head>
<body>
    <div class="footer">{{ config('gh.building') }}, {{ config('gh.institution') }} · {{ $report->title }} · generated {{ $generatedAt }}</div>

    <h1>{{ $report->title }}</h1>
    <div>{{ config('gh.institution') }}, {{ config('gh.city') }}</div>
    <table class="meta">
        <tr><td>Period</td><td>{{ \Illuminate\Support\Carbon::parse($report->from)->format('d/m/Y') }} to {{ \Illuminate\Support\Carbon::parse($report->to)->format('d/m/Y') }}</td></tr>
        <tr><td>Generated by</td><td>{{ $generatedBy }}</td></tr>
        <tr><td>Generated at</td><td>{{ $generatedAt }}</td></tr>
        @if ($report->scopeLabel)<tr><td>Scope</td><td>{{ $report->scopeLabel }}</td></tr>@endif
    </table>

    @if ($report->summary)
        <table class="summary"><tr>
            @foreach ($report->summary as $label => $value)
                <td><strong>{{ $label }}</strong><br>{{ $value }}</td>
            @endforeach
        </tr></table>
    @endif

    <table class="data">
        <thead><tr>
            @foreach ($report->columns as $key => $label)
                <th class="{{ in_array($key, $report->numeric, true) ? 'num' : '' }}">{{ $label }}</th>
            @endforeach
        </tr></thead>
        <tbody>
            @forelse ($report->rows as $row)
                <tr>
                    @foreach ($report->columns as $key => $label)
                        <td class="{{ in_array($key, $report->numeric, true) ? 'num' : '' }}">{{ $row[$key] ?? '—' }}</td>
                    @endforeach
                </tr>
            @empty
                <tr><td colspan="{{ count($report->columns) }}">No records in this period.</td></tr>
            @endforelse
        </tbody>
    </table>

    @if ($report->notes)
        <div class="notes">
            @foreach ($report->notes as $note)<p>{{ $note }}</p>@endforeach
        </div>
    @endif
</body>
</html>
